# Generated by Django 4.0.3 on 2022-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('exp_next_level', models.IntegerField()),
                ('exp_derrota', models.IntegerField(default=0)),
            ],
        ),
    ]
