# Generated by Django 4.0.3 on 2022-03-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_alter_pokemon_exp_derrota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='exp_derrota',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='exp_next_level',
        ),
    ]
