# Generated by Django 4.0.3 on 2022-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_remove_pokemon_exp_remove_pokemon_exp_derrota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='exp',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
